apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-debweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-debweb
    spec:
      containers:
      - name: spinnaker-debweb
        image: chadmoon/debweb
        ports:
        - containerPort: 80
        - containerPort: 3000
        command:
          - "bash"
          - "-c"
          - "cd /debweb; rails s -b 0.0.0.0"