#!/bin/sh
if [ "$1" = "" ]; then
  echo "Usage: kshell <pod>"
  exit 1
fi
COLUMNS=`tput cols`
LINES=`tput lines`
TERM=xterm
GETPOD=`kubectl get pods --selector app=$1 --no-headers=true --all-namespaces`
POD=($GETPOD)
PODID=${POD[1]}
CMD=$2
kubectl exec --namespace spinnaker -i -t $PODID env COLUMNS=$COLUMNS LINES=$LINES TERM=$TERM $2