apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-nodehost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-nodehost
    spec:
      containers:
      - name: spin-nodehost
        image: chadmoon/nodehost
        ports:
        - containerPort: 8000