apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-orca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-orca
    spec:
      volumes:
      - name: spinnaker-config
        secret:
          secretName: spinnaker-config
      containers:
      - name: spin-orca
        volumeMounts:
        - mountPath: /opt/orca/config
          name: spinnaker-config
        image: quay.io/spinnaker/orca
        ports:
        - containerPort: 8083
        resources: 
          limits: 
            memory: 600Mi