apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-portus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-portus
    spec:
      containers:
      - name: spin-portus
        image: chadmoon/portus
        command:
          - "/bin/sh"
          - "-c"
          - "cd /portus; service mysql start; rails s -b 0.0.0.0 -p 3000"
        ports:
        - containerPort: 3000