apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-redis
    spec:
      containers:
      - name: spinnaker-redis
        volumeMounts:
        image: redis
        ports:
        - containerPort: 6379