apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-registryui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-registryui
    spec:
      containers:
      - name: spin-registryui
        image: hyper/docker-registry-web
        ports:
        - containerPort: 8080
        env:
        - name: REGISTRY_URL
          value: http://spin-registry:5000/v2
        - name: REGISTRY_NAME
          value: spin-registry