apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spinnaker-registry
    spec:
      containers:
      - name: spinnaker-registry
        image: registry:2.4.1
        ports:
        - containerPort: 5000