apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-clouddriver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-clouddriver
    spec:
      volumes:
      - name: spinnaker-config
        secret:
          secretName: spinnaker-config
      - name: minikube-config
        secret:
          secretName: minikube-config
      containers:
      - name: spin-clouddriver
        volumeMounts:
        - mountPath: /opt/clouddriver/config
          name: spinnaker-config
        - mountPath: /root/.kube
          name: minikube-config
        image: quay.io/spinnaker/clouddriver
        ports:
        - containerPort: 7002