apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-gate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-gate
    spec:
      volumes:
      - name: spinnaker-config
        secret:
          secretName: spinnaker-config
      containers:
      - name: spin-gate
        volumeMounts:
        - mountPath: /opt/gate/config
          name: spinnaker-config
        image: quay.io/spinnaker/gate
        ports:
        - containerPort: 8084