---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
    load-balancer-spinnaker-gate: "true"
    replication-controller: "spinnaker-gate-v000"
  name: "spinnaker-gate-v000"
  namespace: "spinnaker"
spec:
  replicas: 1
  selector:
    replication-controller: "spinnaker-gate-v000"
  template:
    metadata:
      labels:
        load-balancer-spinnaker-gate: "true"
        replication-controller: "spinnaker-gate-v000"
        app: "spinnaker-gate"
    spec:
      containers:
      - args: []
        command: []
        env: []
        image: "quay.io/spinnaker/gate:latest"
        imagePullPolicy: "Always"
        name: "gate"
        ports:
        - containerPort: 8084
          name: "http"
          protocol: "TCP"
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        volumeMounts:
        - mountPath: "/opt/gate/config"
          name: "spinnaker-config"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "dockerhub"
      - name: "spinnaker-registry"
      - name: "dockerhub"
      - name: "spinnaker-registry"
      restartPolicy: "Always"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30
      volumes:
      - name: "spinnaker-config"
        secret:
          secretName: "spinnaker-config"