---
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
    load-balancer-spinnaker-deck: "true"
    replication-controller: "spinnaker-deck-v000"
  name: "spinnaker-deck-v000"
  namespace: "spinnaker"
spec:
  replicas: 1
  selector:
    replication-controller: "spinnaker-deck-v000"
  template:
    metadata:
      labels:
        load-balancer-spinnaker-deck: "true"
        replication-controller: "spinnaker-deck-v000"
        app: "spinnaker-deck"
    spec:
      containers:
      - args: []
        command: []
        env: []
        image: "localhost:5000/deck:latest"
        imagePullPolicy: "Always"
        name: "deck"
        ports:
        - containerPort: 80
          name: "http"
          protocol: "TCP"
        resources: {}
        terminationMessagePath: "/dev/termination-log"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "dockerhub"
      - name: "spinnaker-registry"
      - name: "dockerhub"
      - name: "spinnaker-registry"
      restartPolicy: "Always"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30